// <auto-generated />
using Biblio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblio.Data.Migrations
{
    [DbContext(typeof(bibliothequeContext))]
    [Migration("20241228170830_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Biblio.Bibliotheque.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date_Publication")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Titre");

                    b.HasKey("Id");

                    b.ToTable("Livres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Auteur = "Antoine de Saint-Exupéry",
                            Date_Publication = "1943",
                            Titre = "Le Petit Prince"
                        },
                        new
                        {
                            Id = 2,
                            Auteur = "Shark",
                            Date_Publication = "unknown",
                            Titre = "SharkNado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
